# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expprobPL <- function(x, sigma, mu, v_ind, q_ind) {
    .Call(`_plising_expprobPL`, x, sigma, mu, v_ind, q_ind)
}

sumSigma <- function(sigma, x, index, v) {
    .Call(`_plising_sumSigma`, sigma, x, index, v)
}

derivativeHelp <- function(x, mu, sigma) {
    .Call(`_plising_derivativeHelp`, x, mu, sigma)
}

mapSigmaIndex <- function(index1, index2, p) {
    .Call(`_plising_mapSigmaIndex`, index1, index2, p)
}

symmetrizeLR <- function(theta) {
    .Call(`_plising_symmetrizeLR`, theta)
}

bootstrapVariances <- function(data, func, sampler, removemissing) {
    .Call(`_plising_bootstrapVariances`, data, func, sampler, removemissing)
}

symmetrizeMatrix <- function(theta) {
    .Call(`_plising_symmetrizeMatrix`, theta)
}

