# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalizingConstant <- function(theta, Esuf, Ess, Z, y) {
    .Call(`_plising_normalizingConstant`, theta, Esuf, Ess, Z, y)
}

symmetrizeMatrix <- function(theta) {
    .Call(`_plising_symmetrizeMatrix`, theta)
}

hessenNorm <- function(thetaH, EsufH, EssH, ZH, yH) {
    .Call(`_plising_hessenNorm`, thetaH, EsufH, EssH, ZH, yH)
}

sumSigma <- function(sigma, x, index, v) {
    .Call(`_plising_sumSigma`, sigma, x, index, v)
}

derivativeHelp <- function(x, mu, sigma) {
    .Call(`_plising_derivativeHelp`, x, mu, sigma)
}

