# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradient_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_plising_gradient_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_plising_gradient_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

gradient_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_plising_gradient_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_plising_gradient_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

gradient_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call(`_plising_gradient_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_plising_hessian_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_plising_hessian_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

hessian_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_plising_hessian_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_plising_hessian_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

hessian_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, cauchy_scale) {
    .Call(`_plising_hessian_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, cauchy_scale)
}

hessian_crossparameters <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_plising_hessian_crossparameters`, interactions, thresholds, observations, no_categories)
}

expprob <- function(x, sigma, mu, v_ind, q_ind) {
    .Call(`_plising_expprob`, x, sigma, mu, v_ind, q_ind)
}

muHessian <- function(x, sigma, mu) {
    .Call(`_plising_muHessian`, x, sigma, mu)
}

sigmaHessian <- function(x, sigma, mu) {
    .Call(`_plising_sigmaHessian`, x, sigma, mu)
}

crossHessian <- function(x, sigma, mu) {
    .Call(`_plising_crossHessian`, x, sigma, mu)
}

singleGradientPL <- function(x, sigma, mu, obs) {
    .Call(`_plising_singleGradientPL`, x, sigma, mu, obs)
}

outerGradient <- function(x, sigma, mu) {
    .Call(`_plising_outerGradient`, x, sigma, mu)
}

expprobPL <- function(x, sigma, mu, v_ind, q_ind) {
    .Call(`_plising_expprobPL`, x, sigma, mu, v_ind, q_ind)
}

sumSigma <- function(sigma, x, index, v) {
    .Call(`_plising_sumSigma`, sigma, x, index, v)
}

derivativeHelp <- function(x, mu, sigma) {
    .Call(`_plising_derivativeHelp`, x, mu, sigma)
}

mapSigmaIndex <- function(index1, index2, p) {
    .Call(`_plising_mapSigmaIndex`, index1, index2, p)
}

symmetrizeLR <- function(theta) {
    .Call(`_plising_symmetrizeLR`, theta)
}

bootstrapVariances <- function(data, func, sampler, removemissing) {
    .Call(`_plising_bootstrapVariances`, data, func, sampler, removemissing)
}

symmetrizeMatrix <- function(theta) {
    .Call(`_plising_symmetrizeMatrix`, theta)
}

